export enum ChannelNames {
    SHOW_OPEN_DIALOG = "show-open-dialog",
    FIND_IMAGES = "find-images",
    FINDED_IMAGES = "find-images",
    START_IMPORTING_IMAGES = "START_IMPORTING_IMAGES",
    END_IMPORTING_IMAGES = "END_IMPORTING_IMAGES",
    UPDATE_IMAGE = "UPDATE_IMAGE",
    DELETE_IMAGE = "DELETE_IMAGE",
    DELETED_IMAGE = "DELETED_IMAGE"
}